### ISSUE TITLE
This is here to inform you that there are better ways of doing bindings.

### ISSUE THREAD

**Issue by eddyb** [arturadib/node-qt#10]
First of all, you are doing a great job.
Second, you're writing vanilla v8 bindings, not the best of things. I had a couple of projects aimed at better bindings.
The one I started with was before node, and is now dead. I thought about rewriting node.js in it, but I didn't have the power to finish that either.
Here's an example: https://github.com/eddyb/gearbox-node/blob/master/src/modules/tty.gear (if it looks bad, it's because of the lack of highlighting).
I had a successful attempt at using a portable version of it in a node module, would you want that?

**Comment by arturadib** [comment]
This is the weirdest comment... Not sure how to respond. Node-Qt is a Node addon, and I'm following the guidelines in Node's addon docs at http://nodejs.org/docs/latest/api/addons.html#addons_addon_patterns (written by yours, truly).

**Comment by eddyb** [comment]
Whatever. Thought you might like being able to write bindings easier. I guess you don't.
