### ISSUE TITLE
App doesn't exit

### ISSUE THREAD

**Issue by darkoverlordofdata** [arturadib/node-qt#16]
I've tried the example apps. They work until I exit the app. The window disappears, but the process remains active until I manually kill it, either via task manager, or ctrl-c in the terminal window.

Thanks,
Bruce

**Comment by charmander** [comment]
Use `QApplication.prototype.exec()` instead of the silly `setInterval` hack.

**Comment by darkoverlordofdata** [comment]
I just tested this, and with one minor correction 

qt = require("node-qt");

it works -Thanks
I haven't worked with qt before, I look forward to learning more about it.

**Comment by charmander** [comment]
Oh, thank you. I was planning to fork it and change the name (npm discourages a `node-` prefix in the actual package name), and I forgot that I had changed that.
