### ISSUE TITLE
Don't depend on node-gyp.

### ISSUE THREAD

**Issue by creationix** [arturadib/node-qt#2]
Npm now has node-gyp built-in.  You shouldn't need to declare it as a dependency anymore.

**Comment by arturadib** [comment]
Hi Tim, thanks for the heads-up. I'm bumping the Node version requirement to >= v0.6.14 (the earliest version I know where npm speaks gyp) and removing the node-gyp dependency.

**Comment by arturadib** [comment]
See 6d16e6eeec2547316128505c905d9fccb3470d13
