### ISSUE TITLE
how to bundle/package for qmake?

### ISSUE THREAD

**Issue by niftylettuce** [arturadib/node-qt#20]
how to do this?

**Comment by waddlesplash** [comment]
What do you mean?

**Comment by niftylettuce** [comment]
For cross platform deploy?

**Comment by waddlesplash** [comment]
You write a script using `node-qt` and then use `npm install node-qt` on all machines. Then you run `node somescript.js`. Why do you need Qmake?

**Comment by niftylettuce** [comment]
I was curious if there was a way to build it so you don't have to use node, e.g. you can use an executable installer.
