### ISSUE TITLE
Assertion `handle->InternalFieldCount() > 0' failed.

### ISSUE THREAD

**Issue by chengluyu** [arturadib/node-qt#23]
Forgive my poor English.`:)`

In my computer, both Windows XP SP3 and Ubuntu 13.04, when I run the example code in `README.md`. It reported error :Assertion `handle->InternalFieldCount() > 0' failed.

The code in `README.md`:

``` js
var qt = require('node-qt'),
    app = new qt.QApplication,
    window = new qt.QWidget;

// Prevent objects from being GC'd
global.app = app;
global.window = window;

// Quirk: the virtual method paintEvent() is mapped into a callback setter
window.paintEvent(function() {
  var p = new qt.QPainter();
  p.begin(window);
  p.drawText(20, 30, 'hello node, hello qt');
  p.end();
});

window.resize(300, 150);
window.show();

// Join Node's event loop
setInterval(app.processEvents, 0);
```

But after I replace the statement 

``` js
setInterval(app.processEvents, 0);
```

 with

``` js
setInterval(function () {
  app.processEvents();
}, 0);
```

It's okay. Is it a bug?

**Comment by manvir-singh** [comment]
i get this too 
![capture](https://f.cloud.github.com/assets/2167740/2036517/0dd361ce-894e-11e3-8a34-39c1caf5fd55.PNG)

**Comment by zzjin23** [comment]
I got same problem on OS X...

**Comment by fredericgermain** [comment]
try this : https://github.com/arturadib/node-qt/pull/29

**Comment by chengluyu** [comment]
Hey folks. I’m cleaning my old issues. I haven’t used it for years and this project seems in stall so I’m gonna close it.
