### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by thecotne** [arturadib/node-qt#33]
i have win7 64bit

```
C:\Users\cotne\Desktop\node-qt>npm install node-qt
npm http GET https://registry.npmjs.org/node-qt
npm http 304 https://registry.npmjs.org/node-qt
npm http GET https://registry.npmjs.org/shelljs/0.0.5-pre4
npm http 304 https://registry.npmjs.org/shelljs/0.0.5-pre4

> node-qt@0.0.2 install C:\Users\cotne\Desktop\node-qt\node_modules\node-qt
> node-gyp rebuild


C:\Users\cotne\Desktop\node-qt\node_modules\node-qt>node "C:\Program Files\nodej
s\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js
" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
.Targets(23,7): error MSB8007: The Platform for project 'qt.vcxproj' is invalid
.  Platform='x64'. You may be seeing this message because you are trying to bui
ld a project without a solution file, and have specified a non-default Platform
 that doesn't exist for this project. [C:\Users\cotne\Desktop\node-qt\node_modu
les\node-qt\build\qt.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\cotne\Desktop\node-qt\node_modules\node-qt
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok
npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-qt@0.0.2 install script.
npm ERR! This is most likely a problem with the node-qt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-qt
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-qt"
npm ERR! cwd C:\Users\cotne\Desktop\node-qt
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\cotne\Desktop\node-qt\npm-debug.log
npm ERR! not ok code 0

```

here is [npm-debug.log](https://gist.githubusercontent.com/thecotne/891de533cccb428640cf/raw/9f79dbaa0d00feab35378f96b791b9ff4c240ea0/npm-debug.log)

**Comment by bineetha** [comment]
Thanks for the mail

On Tue, Sep 23, 2014 at 12:36 PM, cotne nazarashvili <
notifications@github.com> wrote:

> i have win7 64bit
> 
> C:\Users\cotne\Desktop\node-qt>npm install node-qt
> npm http GET https://registry.npmjs.org/node-qt
> npm http 304 https://registry.npmjs.org/node-qt
> npm http GET https://registry.npmjs.org/shelljs/0.0.5-pre4
> npm http 304 https://registry.npmjs.org/shelljs/0.0.5-pre4
> 
> > node-qt@0.0.2 install C:\Users\cotne\Desktop\node-qt\node_modules\node-qt
> > node-gyp rebuild
> 
> C:\Users\cotne\Desktop\node-qt\node_modules\node-qt>node "C:\Program Files\nodej
> s\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js
> " rebuild
> Building the projects in this solution one at a time. To enable parallel build,
> please add the "/m" switch.
> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform
> .Targets(23,7): error MSB8007: The Platform for project 'qt.vcxproj' is invalid
> .  Platform='x64'. You may be seeing this message because you are trying to bui
> ld a project without a solution file, and have specified a non-default Platform
>  that doesn't exist for this project. [C:\Users\cotne\Desktop\node-qt\node_modu
> les\node-qt\build\qt.vcxproj]
> gyp ERR! build error
> gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
> ` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
> npm\node_modules\node-gyp\lib\build.js:267:23)
> gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
> 12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
> les\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\cotne\Desktop\node-qt\node_modules\node-qt
> gyp ERR! node -v v0.10.24
> gyp ERR! node-gyp -v v0.12.1
> gyp ERR! not ok
> npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-qt@0.0.2 install script.
> npm ERR! This is most likely a problem with the node-qt package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls node-qt
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! System Windows_NT 6.1.7601
> npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
> ejs\node_modules\npm\bin\npm-cli.js" "install" "node-qt"
> npm ERR! cwd C:\Users\cotne\Desktop\node-qt
> npm ERR! node -v v0.10.24
> npm ERR! npm -v 1.3.21
> npm ERR! code ELIFECYCLE
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     C:\Users\cotne\Desktop\node-qt\npm-debug.log
> npm ERR! not ok code 0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arturadib/node-qt/issues/33.

## 

With Regards,
Bineetha Jacob,
Mob : +91 8792335855.

**Comment by coderkevin** [comment]
That's a shame.  I got the same in both Windows and Linux.  Looks like this repo isn't being maintained anymore.

**Comment by zhangyi** [comment]
Me too.

**Comment by zhangyi** [comment]
Me too.
