### ISSUE TITLE
build error for mac

### ISSUE THREAD

**Issue by duncup** [arturadib/node-qt#40]
compilation terminated.
make: **\* [Release/obj.target/qt/src/qt.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/steppenwolf/openSource/TalkGG/node_modules/node-qt
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm verb unsafe-perm in lifecycle true
npm info node-qt@0.0.2 Failed to exec install script
npm verb unlock done using /Users/steppenwolf/.npm/_locks/node-qt-96f067b7d3d1086f.lock for /Users/steppenwolf/openSource/TalkGG/node_modules/node-qt
npm verb stack Error: node-qt@0.0.2 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid node-qt@0.0.2
npm verb cwd /Users/steppenwolf/openSource/TalkGG
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "-verbos" "node-qt"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! node-qt@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-qt@0.0.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-qt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-qt
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/node-qt
npm info preuninstall node-qt@0.0.2
npm info uninstall node-qt@0.0.2
npm verb unbuild rmStuff node-qt@0.0.2 from /Users/steppenwolf/openSource/TalkGG/node_modules
npm info postuninstall node-qt@0.0.2
npm verb gentlyRm don't care about contents; nuking /Users/steppenwolf/openSource/TalkGG/node_modules/node-qt

npm ERR! Please include the following file with any support request:

**Comment by Vineetsai** [comment]
Any update how you resolved this issue, as I'm currently seeing similar issue on Mac.
