### ISSUE TITLE
Suggestion of logo

### ISSUE THREAD

**Issue by vdyalex** [arturadib/node-qt#42]
I prepared some presentation about Node QT and had to use some visual mark for that, then I created an easy logo.

![Node QT Logo](http://alexandreazevedo.me/images/node-qt.png)

**Comment by spartucus** [comment]
@alexndreazevedo good idea, but I think it's better to put 'QT' logo under node, just like node.js 's logo.

**Comment by vdyalex** [comment]
I'll try to improve it. Thanks for suggestion, @spartucus.

**Comment by MBach** [comment]
Actually, the logo has changed:
![logo small](http://s3-eu-west-1.amazonaws.com/qt-files/logos/Qt-logo-small.png)
and
![logo Qt company](http://s3-eu-west-1.amazonaws.com/qt-files/logos/The_Qt_Company-logo-small.png)
