### ISSUE TITLE
How to open QTWebkit Windows?

### ISSUE THREAD

**Issue by jaxcore** [arturadib/node-qt#9]
I'll tell you my number 1 request, and a use-case that I think could be a game changer.

Forget all the QT widgets.  Just focus on a way to have NodeJS be able spawn QT application windows that are an instance Webkit pointing to the URL of my choice.

var qtwebkit = require('qtwebkit');
var window = qtwebkit.open('http://myurl');
window.load('http://myurl/newpage.html');
window.close();

That way I can run an NodeJS service in the background, and send messages to it to spawn windows of my choosing.  And I'd like this to be cross platform (Windows, Mac, Linux).

Developing desktop apps in this manner could obliterate Java as a universal write-once run-everywhere platform.

**Comment by tlhunter** [comment]
@jaxcore: you might be interested in the https://github.com/maccman/macgap project, although it unfortunately only works in OS X for now.

**Comment by arturadib** [comment]
Agreed. Care to write some bindings? :)

**Comment by ghost** [comment]
Didn't quite finish it https://github.com/Benvie/node-qt/blob/accessors/src/QtWebkit/qwebview.cc

**Comment by tianshuo** [comment]
Is this done yet?

**Comment by jaxcore** [comment]
This developer has essentially done what I've wanted by directly interfacing with the Chromium libraries without the need for QT:

http://appjs.org/

This is probably a superior solution for a native browser wrapper.  It's a bit buggy, but one hell of a good start.  I'm very impressed.

**Comment by ghost** [comment]
I my work has gone into that instead.
